---
new_page_extension: md
auto_deploy: false
admin_path: src/admin
webhook_url: 'https://stg-api.stackbit.com/project/5d9598e8bebee7001ade7493/webhook/forestry'
sections:
  - type: document
    label: Site Data
    path: src/_data/site.json
    templates:
      - site_data
  - type: document
    label: Navigation
    path: src/_data/navigation.json
    templates:
      - navigation
  - type: document
    label: Theme Settings
    path: src/_data/tokens.json
    templates:
      - settings
  - type: document
    label: Homepage
    path: src/index.md
    templates:
      - home
  - type: directory
    path: src/pages
    match: '**/*'
    label: Pages
    create: all
    templates:
      - page
  - type: directory
    path: src/posts
    match: '**/*'
    label: Posts
    create: all
    templates:
      - post
  - type: document
    label: Posts Archive
    path: src/archive.md
    templates:
      - archive
upload_dir: src/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
